github: xxxcoder-ui
patreon:
open_collective: # Replace with a single Open Collective username
ko_fi: xxxcoder
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: xxxcoder-ui
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
thanks_dev: xxxcoder-ui
